# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='user_pics/'),
        ),
    ]
