# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 17:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='profile_pictures/')),
                ('car_picture', models.ImageField(upload_to='pictures/')),
                ('number_plates', models.CharField(max_length=30)),
                ('capacity', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=30)),
                ('city', models.CharField(max_length=60)),
                ('bio', models.CharField(blank=True, max_length=140)),
                ('gender', models.CharField(choices=[('F', 'female'), ('M', 'male'), ('Both', 'both'), ('None', 'non-specified')], default='None', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
